version: "3.9"
services:
  mssql:
    container_name: test-mssql
    build:
      context: ./scripts/mssql
    restart: always
    ports:
      - 1437:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
      MSSQL_PID: Express
    volumes:
      - ./scripts/mssql/script.sql:/docker-entrypoint-initdb.d/script.sql
  mariadb:
    container_name: test-mariadb
    image: mariadb:11.1.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 3307:3306
    volumes:
      - ./scripts/mariadb/script.sql:/docker-entrypoint-initdb.d/script.sql
  mysql:
    container_name: test-mysql
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 3308:3306
    volumes:
      - ./scripts/mysql/script.sql:/docker-entrypoint-initdb.d/script.sql
  postgres:
    container_name: test-postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5434:5432
    volumes:
      - ./scripts/postgres/script.sql:/docker-entrypoint-initdb.d/script.sql
  mongo:
    container_name: test-mongo
    image: mongo:7.0.2-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017



